# Generated by Django 5.2.7 on 2026-01-26 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specilaiz', models.CharField(choices=[('General Checkup', 'General Checkup'), ('Teeth cleaning', 'Teeth cleaning'), ('Teeth Whitening', 'Teeth Whitening'), ('Root Canal', 'Root Canal'), ('Dental Implants', 'Dental Implants'), ('Emergency Care', 'Emergency Care')], default='General Checkup')),
                ('Dr_image', models.ImageField(upload_to='Doctors')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
